parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Proglab\ComponentBundle\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'
    public: true